type Product {
  id: ID!
  name: String!
  description: String!
  quantity: Int!
  expiredDate: Date

  user: User!
}

extend type Query {
  GetProducts: [Product!]
  GetProductWithID(id: ID!): Product!
}

input CreateProduct {
  name: String!
  description: String!
  quantity: Int!
  expiredDate: Date
}

input UpdateProduct {
  id: ID!
  name: String!
  description: String!
  quantity: Int!
  expiredDate: Date
}

extend type Mutation {
  CreateProduct(input: CreateProduct!): Product! @auth
  UpdateProduct(input: UpdateProduct!): Product! @auth
}