version: '2'

services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5001:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
      - POSTGRESQL_USERNAME=customuser
      - POSTGRESQL_PASSWORD=custompassword
      - POSTGRESQL_DATABASE=customdatabase
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
volumes:
  pg_0_data:
    driver: local




# version: '2'  # Keep this at the top.

# services:
#   pg-0:
#     image: bitnami/postgresql-repmgr:14
#     ports:
#       - 5001:5432
#     volumes:
#       - pg_0_data:/bitnami/postgresql
#     environment:
#       - POSTGRESQL_POSTGRES_PASSWORD=adminpassword
#       - POSTGRESQL_USERNAME=customuser
#       - POSTGRESQL_PASSWORD=custompassword
#       - POSTGRESQL_DATABASE=customdatabase
#       - REPMGR_PASSWORD=repmgrpassword
#       - REPMGR_PRIMARY_HOST=pg-0
#       - REPMGR_PARTNER_NODES=pg-0,pg-1
#       - REPMGR_NODE_NAME=pg-0
#       - REPMGR_NODE_NETWORK_NAME=pg-0

# volumes:
#   pg_0_data:
#     driver: local
