package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"learn-graphql-go-gorm/datalayer/models"
	"learn-graphql-go-gorm/graph/model"
	"learn-graphql-go-gorm/middlewares"
	"learn-graphql-go-gorm/servicemodels"
	"strconv"
)

// CreateProduct is the resolver for the CreateProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProduct) (*model.Product, error) {
	// Secure - requires authentication
	user, err := middlewares.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	req := servicemodels.CreateProduct{
		BaseProduct: servicemodels.BaseProduct{
			Name:        input.Name,
			Description: input.Description,
			Quantity:    int(input.Quantity),
			ExpiredDate: &input.ExpiredDate.Time,
		},
	}

	product, err := r.ProductService.Create(ctx, user, req)
	return product.ProductToGraphQLProduct(), err
}

// UpdateProduct is the resolver for the UpdateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProduct) (*model.Product, error) {
	// Secure - requires authentication
	_, err := middlewares.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	id, err := strconv.Atoi(input.ID)
	if err != nil {
		return nil, err
	}

	req := servicemodels.UpdateProduct{
		ID: uint(id),
		BaseProduct: servicemodels.BaseProduct{
			Name:        input.Name,
			Description: input.Description,
			Quantity:    int(input.Quantity),
			ExpiredDate: &input.ExpiredDate.Time,
		},
	}

	product, err := r.ProductService.Update(ctx, req)
	return product.ProductToGraphQLProduct(), err
}

// GetProducts is the resolver for the GetProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	// Public - no auth needed
	products, err := r.ProductService.GetProductList(ctx, nil)
	if err != nil {
		return nil, err
	}
	return models.ProductListToGraphQLProductList(products), nil
}

// GetProductWithID is the resolver for the GetProductWithID field.
func (r *queryResolver) GetProductWithID(ctx context.Context, id string) (*model.Product, error) {
	// Public - no auth needed
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}

	product, err := r.ProductService.GetProductByID(ctx, uint(idInt))
	if err != nil {
		return nil, err
	}

	return product.ProductToGraphQLProduct(), nil
}

// GetProductsPagination is the resolver for the GetProductsPagination field.
func (r *queryResolver) GetProductsPagination(ctx context.Context, pagination *model.PaginationInput) (*model.PaginatedProducts, error) {
	// Public - no auth needed
	query := servicemodels.ProductQuery{
		PaginationRequest: servicemodels.PaginationRequest{PageNo: int(pagination.Page), PerPage: int(pagination.Limit)},
	}

	products, err := r.ProductService.GetProductList(ctx, &query)
	if err != nil {
		return nil, err
	}

	response := models.ProductListToPaginatedProducts(products, query)

	return &response, nil
}
