package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"learn-graphql-go-gorm/graph/model"
	"learn-graphql-go-gorm/services/product_service"
)

// ProductChanged is the resolver for the productChanged field.
func (r *subscriptionResolver) ProductChanged(ctx context.Context) (<-chan *model.ProductChangeEvent, error) {
	broadcaster := product_service.GetBroadcaster() // Get the broadcaster
	events := broadcaster.Subscribe()               // Register this client
	return events, nil                              // Return channel to gqlgen
}
