package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"learn-graphql-go-gorm/graph/model"
)

// CreateProduct is the resolver for the CreateProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProduct) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - CreateProduct"))
}

// UpdateProduct is the resolver for the UpdateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, input model.UpdateProduct) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - UpdateProduct"))
}

// GetProducts is the resolver for the GetProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProducts - GetProducts"))
}

// GetProductWithID is the resolver for the GetProductWithID field.
func (r *queryResolver) GetProductWithID(ctx context.Context, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: GetProductWithID - GetProductWithID"))
}
