package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"learn-graphql-go-gorm/graph/model"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input model.Register) (string, error) {
	panic(fmt.Errorf("not implemented: Register - Register"))
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	panic(fmt.Errorf("not implemented: Login - Login"))
}

// GetUsers is the resolver for the GetUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUsers - GetUsers"))
}

// GetUserWithID is the resolver for the GetUserWithID field.
func (r *queryResolver) GetUserWithID(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUserWithID - GetUserWithID"))
}
