services:
  user-service:
    image: user-service:latest # Assigns a name and tag to the built image
    build:
      context: ./              # The directory containing the Dockerfile
      # You can specify a different Dockerfile name if it's not named 'Dockerfile'
      # dockerfile: Dockerfile.dev   
    ports:
      - "4000:4000"                   # Maps host port 8000 to container port 8000
    volumes:
      - ./:/app                # Mounts the local directory into the container
    networks:
      - user-service-networks
      - product-service_product-service-networks

networks:
  user-service-networks:
  product-service_product-service-networks: # This is the external network that is created by product-service, the name is product-service_product-service-networks because the name of the service is product-service and the name of the network is product-service-networks, and the underscore is added by docker compose (docker compose auto-prefix names)
    external: true