// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"learn-graphql-go-gorm/graph/scalars"
	"strconv"
)

type CreateProduct struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
}

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PaginatedProducts struct {
	Products   []*Product      `json:"products,omitempty"`
	Pagination *PaginationInfo `json:"pagination"`
}

type PaginationInfo struct {
	TotalData   int32 `json:"totalData"`
	TotalPages  int32 `json:"totalPages"`
	HasNextPage bool  `json:"hasNextPage"`
}

type PaginationInput struct {
	Page  int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type Product struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
	User        *User         `json:"user"`
}

type ProductChangeEvent struct {
	Action    ProductAction `json:"action"`
	Product   *Product      `json:"product"`
	Timestamp string        `json:"timestamp"`
}

type Query struct {
}

type Register struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Subscription struct {
}

type UpdateProduct struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProductAction string

const (
	ProductActionCreated ProductAction = "CREATED"
	ProductActionUpdated ProductAction = "UPDATED"
)

var AllProductAction = []ProductAction{
	ProductActionCreated,
	ProductActionUpdated,
}

func (e ProductAction) IsValid() bool {
	switch e {
	case ProductActionCreated, ProductActionUpdated:
		return true
	}
	return false
}

func (e ProductAction) String() string {
	return string(e)
}

func (e *ProductAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductAction", str)
	}
	return nil
}

func (e ProductAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
