// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProduct struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Quantity    int32  `json:"quantity"`
}

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Product struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Quantity    int32  `json:"quantity"`
	User        *User  `json:"user"`
}

type Query struct {
}

type Register struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UpdateProduct struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Quantity    int32  `json:"quantity"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
