// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"learn-graphql-go-gorm/graph/scalars"
)

type CreateProduct struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
}

type Login struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PaginatedProducts struct {
	Products   []*Product      `json:"products,omitempty"`
	Pagination *PaginationInfo `json:"pagination"`
}

type PaginationInfo struct {
	TotalData   int32 `json:"totalData"`
	TotalPages  int32 `json:"totalPages"`
	HasNextPage bool  `json:"hasNextPage"`
}

type PaginationInput struct {
	Page  int32 `json:"page"`
	Limit int32 `json:"limit"`
}

type Product struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
	User        *User         `json:"user"`
}

type Query struct {
}

type Register struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UpdateProduct struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Quantity    int32         `json:"quantity"`
	ExpiredDate *scalars.Date `json:"expiredDate,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
