version: '2'

networks:
  my-network:
    driver: bridge

services:
  pg-0:
    image: postgres:14
    ports:
      - 5001:5432
    volumes:
      - pg_0_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_USER=customuser
      - POSTGRES_DB=customdatabase
      - PGDATA=/var/lib/postgresql/data
    command: |
      bash -c "postgres -c 'wal_level=replica' -c 'max_wal_senders=3' -c 'hot_standby=on' && \
        echo 'host replication all pg-1 md5' >> $PGDATA/pg_hba.conf && \
        echo 'host replication all pg-0 md5' >> $PGDATA/pg_hba.conf && \
        exec postgres"

  pg-1:
    image: postgres:14
    ports:
      - 5002:5432
    volumes:
      - pg_1_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_USER=customuser
      - POSTGRES_DB=customdatabase
      - PGDATA=/var/lib/postgresql/data
    command: |
      bash -c "until pg_isready -h pg-0 -p 5432; do sleep 2; done && \
        pg_basebackup -h pg-0 -D $PGDATA -U customuser -v -P --wal-method=stream && \
        echo 'standby_mode = on' >> $PGDATA/recovery.conf && \
        echo 'primary_conninfo = \"host=pg-0 port=5432 user=customuser password=adminpassword\"' >> $PGDATA/recovery.conf && \
        exec postgres"

  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5435:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=customuser
      - PGPOOL_SR_CHECK_PASSWORD=adminpassword
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=adminpassword
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=adminpassword
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
