type Link {
  id: ID!
  title: String!
  address: String!
  user: User!
}

# THis is user bro
type User {
  id: ID!
  name: String!
}

# NEW
type Customer {
  id: ID!
  name: String!
  email: String!
}

type Query {
  links: [Link!]!
  users: [User!]!
  customers: [Customer!]!
  customerWithID(id: ID!): Customer!
}

input NewLink {
  title: String!
  address: String!
}

# NEW
input NewCustomer {
  name: String!
  email: String!
}

input RefreshTokenInput{
  token: String!
}

input NewUser {
  username: String!
  password: String!
}

input Login {
  username: String!
  password: String!
}

type Mutation {
  createLink(input: NewLink!): Link!
  createUser(input: NewUser!): String!
  login(input: Login!): String!
  refreshToken(input: RefreshTokenInput!): String!
  createCustomer(input: NewCustomer!): String!
}