package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"learn-graphql-go-gorm/graph/model"
	"learn-graphql-go-gorm/internal/auth"
	"learn-graphql-go-gorm/internal/links"
	"learn-graphql-go-gorm/internal/pkg/jwt"
	"learn-graphql-go-gorm/internal/users"
)

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input model.NewLink) (*model.Link, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		return &model.Link{}, fmt.Errorf("access denied")
	}

	link := links.Link{
		Title:   input.Title,
		Address: input.Address,
		User:    user,
	}

	linkID, err := link.Save()
	graphqlUser := &model.User{
		ID:   fmt.Sprintf("%d", user.ID),
		Name: user.Username,
	}

	return &model.Link{ID: fmt.Sprintf("%d", linkID), Title: link.Title, Address: link.Address, User: graphqlUser}, err
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	var user users.User
	user.Username = input.Username
	user.Password = input.Password
	if err := user.Create(); err != nil {
		return "", err
	}
	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		return "", err
	}
	return token, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	var user users.User
	user.Username = input.Username
	user.Password = input.Password
	correct, _ := user.Authenticate()
	if !correct {
		// 1
		return "", &users.WrongUsernameOrPasswordError{}
	}
	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		return "", err
	}
	return token, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	username, err := jwt.ParseToken(input.Token)
	if err != nil {
		return "", fmt.Errorf("access denied")
	}
	token, err := jwt.GenerateToken(username)
	if err != nil {
		return "", err
	}
	return token, nil
}

// CreateCustomer is the resolver for the createCustomer field.
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.NewCustomer) (string, error) {
	return "1", nil
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	var (
		resultLinks []*model.Link
		dbLinks     []links.Link
		err         error
	)

	dbLinks, err = links.GetAll()
	for _, link := range dbLinks {
		resultLinks = append(resultLinks, &model.Link{ID: fmt.Sprintf("%d", link.ID), Title: link.Title, Address: link.Address})
	}
	return resultLinks, err
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return []*model.User{
		{ID: "0", Name: "pewpew"},
	}, nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	// var customers []*model.Customer
	// customers = append(customers, &model.Customer{
	// 	ID:    "1",
	// 	Name:  "nando",
	// 	Email: "nando@mail.co",
	// })

	// return customers, nil

	return nil, fmt.Errorf("error fetching customer")
}

// CustomerWithID is the resolver for the customerWithID field.
func (r *queryResolver) CustomerWithID(ctx context.Context, id string) (*model.Customer, error) {
	var user model.Customer
	return &user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
